// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9hUVo52qEev6HsT4ssftbAjO1Gfg1r4',
    appId: '1:58764827344:web:8483a23dc30c3d551bdcd5',
    messagingSenderId: '58764827344',
    projectId: 'flutter-app-2ec00',
    authDomain: 'flutter-app-2ec00.firebaseapp.com',
    databaseURL: 'https://flutter-app-2ec00-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-2ec00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEMdKk1GSc2M3oTf6YIruSrILNh8t13o',
    appId: '1:58764827344:android:7dd99f3daef93c9f1bdcd5',
    messagingSenderId: '58764827344',
    projectId: 'flutter-app-2ec00',
    databaseURL: 'https://flutter-app-2ec00-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-2ec00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZxG2fIJ4NYALGPItpvKgvXb7MqYz1G48',
    appId: '1:58764827344:ios:e45e4191fe9a3e1e1bdcd5',
    messagingSenderId: '58764827344',
    projectId: 'flutter-app-2ec00',
    databaseURL: 'https://flutter-app-2ec00-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-2ec00.appspot.com',
    iosClientId: '58764827344-jj76hna31u1mk0v9ve4l24qltndpaq89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZxG2fIJ4NYALGPItpvKgvXb7MqYz1G48',
    appId: '1:58764827344:ios:e45e4191fe9a3e1e1bdcd5',
    messagingSenderId: '58764827344',
    projectId: 'flutter-app-2ec00',
    databaseURL: 'https://flutter-app-2ec00-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-2ec00.appspot.com',
    iosClientId: '58764827344-jj76hna31u1mk0v9ve4l24qltndpaq89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
